### ISSUE TITLE
Difficulties with the installation process

### ISSUE THREAD

**Issue by enzi96** [playgameservices/management-tools#20]
I ran the "bower install" command in the git window after which I got to this line where you say "With the dependencies set, serve the demo-utils folder from a web server.". Here I got confused. What does serve the folder from a web server mean? And where is this folder?

Bascially, I managed to follow the steps down to bower install. Then I'm not sure what I'm supposed to do. Could you please help me, by giving me more detailed steps that I need to follow?

**Comment by gguuss** [comment]
You can serve the web pages using any web server, for example, Python's built-in web server can be started locally on port 8000 using `python -m SimpleHTTPServer 8000`, Apache's web server can be configured to run using various installers such as MaMP, WaMP; IIS can be run on Windows;  NPM can install a basic server, `npm install http-server -g` ... `http-server`. We don't document it because there are so many options.
